"""add short link ownership

Revision ID: 4f3dce7a6735
Revises: 915d9764112f
Create Date: 2026-09-09 11:46:07.311273

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f3dce7a6735"
down_revision: str | Sequence[str] | None = "915d9764112f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("short_links", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.execute(
        sa.text(
            """
                UPDATE short_links
                SET owner_id = users.id
                FROM users
                WHERE users.email = 'student@example.com'
                """
        )
    )
    op.alter_column(
        "short_links",
        "owner_id",
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.create_index(op.f("ix_short_links_owner_id"), "short_links", ["owner_id"], unique=False)
    op.create_foreign_key(
        "fk_short_links_owner_id_users", "short_links", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_short_links_owner_id_users", "short_links", type_="foreignkey")
    op.drop_index(op.f("ix_short_links_owner_id"), table_name="short_links")
    op.drop_column("short_links", "owner_id")
    # ### end Alembic commands ###
