"""add link expiration

Revision ID: a71eee84491e
Revises: 4f3dce7a6735
Create Date: 2026-09-10 14:43:36.296163

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a71eee84491e"
down_revision: str | Sequence[str] | None = "4f3dce7a6735"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("short_links", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("short_links", "expires_at")
    # ### end Alembic commands ###
